baseURL = "https://jjylab.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "JJy"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

[permalinks]
posts = "/posts/:slugorcontentbasename/"

[params]
name = "JJy"
github = "https://github.com/jjyr"
x = "https://x.com/jjybtw"
email = "jjyruby@gmail.com"
about_items = [
  "ğŸ§‘â€ğŸ’»å·¥ä¸šé©å‘½ä¸­çš„ç»‡æœºå·¥",
  "ğŸŒŠå°è¯•ç”¨ AI åœ¨æŠ€æœ¯æµªæ½®ä¸­ç”Ÿå­˜",
  "ğŸ’°AIã€Œç‚¼é‡‘æœ¯ã€ç»ƒä¹ è€…ï¼ˆè‚¡ç¥¨ / åŒºå—é“¾ï¼‰",
  "ğŸ“–ç§‘å¹»å°è¯´ä¿¡ä¼—",
]
about_quote = "æ˜ç™½å“ªäº›äº‹è¯¥è®¤çœŸå¯¹å¾…ï¼Œå…¶ä½™çš„å°±ä¸€ç¬‘ç½®ä¹‹å§ã€‚"
